import { AppConfig } from "../global.slint";
import { ScrollView } from "std-widgets.slint";
import { ListItemPanel } from "list-item-panel.slint";

export component ItemPanel inherits Rectangle {
    background: AppConfig.color_primary.darker(20%);
    border-top-left-radius: 5px;
    border-top-right-radius: 5px;
    min-height: 140px;
    min-width: 140px;

    ScrollView {
        property <length> height_offset: 2px;
        property <length> width_offset:  4px;

        padding: 3px;
        height: parent.height;
        width: parent.width;
        viewport-height: (AppConfig.list-items.length * 48px) + 2px;
        viewport-width: parent.width;

        VerticalLayout {
            width: parent.width * 96%;
            x: parent.x + 4px;
            y: parent.y + 2px;

            for list-item[i] in AppConfig.list-items: ListItemPanel {
                completed: list-item.completed;
                description: list-item.description;
                datetime: list-item.datetime;
                id: i;
            }
        }
    }

    Text {
        visible: AppConfig.list-items.length < 1;
        color: AppConfig.color_secondary;
        text: "Nothing TODO!";
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}
