export struct ListItem {
    completed: bool,
    description: string,
    datetime: string,
}

export global AppConfig {
    out property <color> color_primary: grey;
    out property <color> color_secondary: lightgrey;
    out property <color> color_tertiary: #75abe6;
    in property <string> data_path: ".todo.dat";
    out property <length> font-size: 14px;
    in property <[ListItem]> list-items: [];
}

export global AppLogic {
    callback load_list_items();
    callback dump_list_items();
    callback pop_list_item(int) -> ListItem;
    callback put_list_item(int, ListItem);
}

// { completed: false, description: "Take Dog for Walk" },
// { completed: false, description: "Write Research Paper" },
// { completed: false, description: "Make Grocery List" },
